###################### PHYSICS LIST OPTIONS #############################################
/DetSys/phys/SelectPhysics emlivermorepolarized
/run/initialize
#/process/em/fluo true
#/process/em/auger true
#/process/em/pixe true


###################### GRIFFIN DETECTOR PROPERTIES ######################################
#SetCustomShieldsPresent 1 (include suppressors)
#SetCustomShieldsPresent 0 (do NOT include suppressors)
#SetCustomShieldsPresent -1 (only include side and back suppressors, ie. no extension)
#SetCustomRadialDistance 11 cm (leave this at 11 cm, even in back mode)
#SetCustomExtensionSuppressorLocation 0 (forward mode)
#SetCustomExtensionSuppressorLocation 1 (back mode)
#includeGriffinHevimet 0 (no)
#includeGriffinHevimet 1 (yes)
#########################################################################################
/DetSys/det/SetCustomShieldsPresent 0
/DetSys/det/SetCustomRadialDistance 11 cm
/DetSys/det/SetCustomExtensionSuppressorLocation 0
/DetSys/det/includeGriffinHevimet 0

/DetSys/det/SetCustomPosition 1 1 0
/DetSys/det/addGriffinCustomDetector 1
#/DetSys/det/SetCustomPosition 2 2 0
#/DetSys/det/addGriffinCustomDetector 2
#/DetSys/det/SetCustomPosition 3 3 0
#/DetSys/det/addGriffinCustomDetector 3
#/DetSys/det/SetCustomPosition 4 4 0
#/DetSys/det/addGriffinCustomDetector 4
/DetSys/det/SetCustomPosition 5 5 0
/DetSys/det/addGriffinCustomDetector 5
/DetSys/det/SetCustomPosition 6 6 0
/DetSys/det/addGriffinCustomDetector 6
/DetSys/det/SetCustomPosition 7 7 0
/DetSys/det/addGriffinCustomDetector 7
#/DetSys/det/SetCustomPosition 8 8 0
#/DetSys/det/addGriffinCustomDetector 8
#/DetSys/det/SetCustomPosition 9 9 0
#/DetSys/det/addGriffinCustomDetector 9
#/DetSys/det/SetCustomPosition 10 10 0
#/DetSys/det/addGriffinCustomDetector 10
#/DetSys/det/SetCustomPosition 11 11 0
#/DetSys/det/addGriffinCustomDetector 11
#/DetSys/det/SetCustomPosition 12 12 0
#/DetSys/det/addGriffinCustomDetector 12
/DetSys/det/SetCustomPosition 13 13 0
/DetSys/det/addGriffinCustomDetector 13
#/DetSys/det/SetCustomPosition 14 14 0
#/DetSys/det/addGriffinCustomDetector 14
#/DetSys/det/SetCustomPosition 15 15 0
#/DetSys/det/addGriffinCustomDetector 15
#/DetSys/det/SetCustomPosition 16 16 0
#/DetSys/det/addGriffinCustomDetector 16

###################### LaBr3 DETECTOR PROPERTIES ########################################
#addLanthanumBromide #_of_dets radial_pos_in_cm null
#addAncillaryBGO #_of_dets radial_pos_in_cm include_hevimet
#/DetSys/det/addLanthanumBromide 8 16.5 0
#/DetSys/det/addAncillaryBGO 8 16.5 0

###################### SCEPTAR and Others ###############################################
#/DetSys/det/addSceptar 20
#/DetSys/app/add8piVacuumChamber
#/DetSys/app/add8piVacuumChamberAuxMatShell 20 mm

###################### VERBOSE LEVELS ###################################################
/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0


###################### RUN VRML VIS #####################################################
#/control/execute vis.mac
#/vis/scene/endOfEventAction accumulate 500

###################### USER DEFINED RAD DECAY FILES #####################################
#/grdm/setRadioactiveDecayFile 27 60 UserData/UserRadData_z27.a60
#/grdm/setPhotoEvaporationFile 28 60 UserData/UserEvapData_z28.a60

###################### RAD DECAY, EFF SIM, LaBr3 DECAY SIM ##############################
#/gun/particle ion
#/gun/ion 27 60
#/grdm/nucleusLimits 60 60 27 27



/gun/particle gamma
/DetSys/gun/efficiencyEnergy 1000 keV
/DetSys/gun/direction 4.2095 10.1627 0
/DetSys/gun/beamRadius 3 cm
#/DetSys/gun/polarization 10.1627 -4.2095 0
/DetSys/gun/polarization 0 0 1



###################### BEAM ON ##########################################################

/run/beamOn 1000000
