# Set verbose level
/run/verbose 0

#################################################
# Visualization of detector geometry with 
# the VRML2FILE driver.
#################################################

# Invoke the VRML2FILE driver
#/vis/open VRML2FILE

# Visualize of the whole detector geometry
#/vis/viewer/set/style surface
#/vis/drawVolume
#/vis/viewer/update

#################################################
# Visualization of detector geometry and events 
# with the VRML2FILE driver.
#################################################

# Invoke the VRML2FILE driver
/vis/open VRML2FILE

# Set viewer rendering style
# "wireframe" means  "half-transparent" in VRML2FILE driver 
/vis/viewer/set/style surface
#/vis/viewer/set/style wireframe

# Compund command: creates scene, adds volume, attaches scene handler
# and refreshes viewer
/vis/drawVolume

# Create a new scene 
/vis/scene/create

# Attach the current scene handler to the current scene
/vis/sceneHandler/attach 

# Add the world volume to the current scene
/vis/scene/add/volume

# Visualize one event added to the current scene
# * Command "/vis/scene/notifyHandlers" is written in 
#   XrayTelRunAction::BeginOfRunAction()
# * Command "/vis/viewer/update" is written in 
#   XrayTelRunAction::EndOfRunAction()

############# Don't Work ##############################################
# Store particle trajactories for visualization
#/tracking/storeTrajectory 1

# Set to draw tracks of positively charged particles
#/event/drawTracks charged
#######################################################################

# Add coordinate axes at origin
# red color for x-axis
# green color for y-axis
# blue color for z-axis
/vis/scene/add/axes 0 0 0 500 mm

# Add trajectories to the visualization.
/vis/scene/add/trajectories smooth

# Add hits to scene
/vis/scene/add/hits

# Accumulate multiple events in one picture.
/vis/scene/endOfEventAction accumulate

# ----------------
# Trajectory Colouring Scheme
# ----------------
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/set -1 blue
#/vis/modeling/trajectories/drawByCharge-0/set 1 blue
#/vis/modeling/trajectories/drawByCharge-0/set 0 green

#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- magenta
#/vis/modeling/trajectories/drawByParticleID-0/set proton magenta
#/vis/modeling/trajectories/drawByParticleID-0/set gamma green
#/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow

# Disable visualization
#/vis/disable

# ----------------
# Beam Characteristics
# ----------------
# Change primary particle
#/gun/particle gamma
#/gun/particle e-
#/gun/particle proton
#/gun/particle neutron
#/gun/particle geantino

# Set General Particle Source options
#/gps/particle proton
#/gps/pos/type Plane
#/gps/pos/shape Annulus
#/gps/pos/rot1 0. 0. 1.
#/gps/pos/rot2 0. 1. 0.
#/gps/pos/radius 35.5 cm
#/gps/pos/inner_radius 30.5 cm
#/gps/pos/centre 780.1 0. 0. cm
#/gps/ang/type cos
#/gps/ang/rot1 0. 0. 1.
#/gps/ang/rot2 0. 1. 0.
#/gps/ang/maxtheta 1. deg
#/gps/ene/type Mono
#/gps/ene/mono 0.5 MeV

# Set number of particles and start
#/run/beamOn 1











